spring:
  application:
    name: email-service
  kafka:
    bootstrapServers: http://localhost:29092

email:
  username: ${MAIL_USERNAME}
  password: ${MAIL_PASSWORD}

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
      base-path: /actuator/emails