spring:
  application:
    name: hotel-service
  datasource:
    url: jdbc:postgresql://servicio-PostgreSQL:5432/msvc_hotel
    username: postgres
    password: ${POSTGRES_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka
